"""add_schedule_configs_table

Revision ID: 894fb6aa1392
Revises: 000aa5b45b1e
Create Date: 2025-12-16 16:25:06.997444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '894fb6aa1392'
down_revision = '000aa5b45b1e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
